### ISSUE TITLE
Policy Server crashes when receiving a request on arm64

### ISSUE THREAD

**Issue by ereslibre** [kubewarden/policy-server#128]
https://github.com/kubewarden/docs/issues/75 describes how to make the Policy Server crash under arm64, but just trying to follow the quick start makes it crash on every request.

**Comment by chrisns** [comment]
temp workaround:
```
apiVersion: policies.kubewarden.io/v1alpha2
kind: PolicyServer
metadata:
  name: default
spec:
  image: ghcr.io/kubewarden/policy-server:latest@sha256:682b9f9c6f86b62b0673b695897ca834d415d9ad24736edcee8c4bfa7adf2dca
```
to force the use of the amd64 image
