### ISSUE TITLE
EPIC: verification of policies signed using sigstore's keyless signing

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#142]
Policy server must be able to verify policies that have been signed using Sigstore's keyless signing.

The verification requires the user to provide a list of email addresses that are expected to be inside of the certificate issued by Fulcio.

## Implementation details

The [`verification.yaml`](https://github.com/kubewarden/policy-server/wiki/Configuration#verification---verification-path) file should be enriched to have also another top level key: `cert_emails`.

This is how the file will look like:

```yaml
---
verification_keys: #optional
  key-name-irrelevant: |
            -----BEGIN PUBLIC KEY-----
            MBFKHFDGHKIJH0CAQYIKoZIzj0DAQcDQgAEX0HFTtCfTtPmkx5p1RbDE6HJSGAVD
            BVDF6SKFSF87AASUspkQsN3FO4iyWodCy5j3o0CdIJD/KJHDJFHDFIu6sA==
            -----END PUBLIC KEY-----
  another-key: |
            -----BEGIN PUBLIC KEY-----
            AUYSDHKJFGSHGSHCAQYIKoZIzj0DAQcDQgAEX0HFTtCfTtPmkx5p1RbtwDE1EVzu
            wjQs1cCRKb5Pz/yUspkQsN3FO4iyWodCy5j3o0CdIJD/1gvq98pf4IG9tA==
            -----END PUBLIC KEY-----
cert_emails: #optional 
- flavio@foo.bar.com   
- victor@foo.bar.com
verification_annotations: # optional
  env: prod
  foo: bar
```

All the `cert_emails` mentioned must be found inside of the policy signatures. This is the same behaviour of multiple `verification_keys`.

The following table shows the behaviour of the verification check, depending on what the user provides

| verification keys | cert emails | annotations | outcome |
|-----------------------|----------------|-----------------|-------------|
| ✅ | ❌ | ❌ | each policy must be signed with all the specified verification keys |
| ✅ | ✅ | ❌ | each policy must be signed with all the specified verification keys **and** with all the specified emails |
| ✅ | ✅ | ✅ | each policy must be signed with all the specified verification keys **and** with all the specified emails; plus each signature must satisfy all the annotations provided by the user |
| ✅ | ❌ | ✅ | each policy must be signed with all the specified verification keys; plus each signature must satisfy all the annotations provided by the user |
| ❌ | ✅ | ✅ | each policy must be signed with all the specified emails; plus each signature must satisfy all the annotations provided by the user |
| ❌ | ❌ | ✅ | I don't think scenario makes any sense, we should error out when the configuration looks like that |
