### ISSUE TITLE
Pull policy from on-premise registry fails with error "unknown scheme"

### ISSUE THREAD

**Issue by Martin-Weiss** [kubewarden/policy-server#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Deploy kubewarden-default with default policies enabled and re-directed to on-premise registry.

I.e. using registry01.suse:5000/rke-prod/ghcr.io/kubewarden/policies/user-group-psp:v0.2.0

In the container logs I can see this:
`
2022-11-22T15:51:33.872255Z ERROR policy_server: error while downloading policy clusterwide-no-host-namespace-sharing from registry01.suse:5000/rke-prod/ghcr.io/kubewarden/policies/host-namespaces-psp:v0.1.2: unknown scheme: registry01.suse`

### Expected Behavior

Pull from the on-premise registry works.

### Steps To Reproduce

Put required policies into on-premise registry (I am using registry:2.8.1)

Deploy helm chart for kubewarden-default with adjusted values for images

```
    recommendedPolicies:
      enabled: true
...
      recommendedPolicies:
        allowPrivilegeEscalationPolicy:
          module: "registry01.suse:5000/rke-prod/ghcr.io/kubewarden/policies/allow-privilege-escalation-psp:v0.1.11"
        hostNamespacePolicy:
          module: "registry01.suse:5000/rke-prod/ghcr.io/kubewarden/policies/host-namespaces-psp:v0.1.2"
        podPrivilegedPolicy:
          module: "registry01.suse:5000/rke-prod/ghcr.io/kubewarden/policies/pod-privileged:v0.2.1"
        userGroupPolicy:
          module: "registry01.suse:5000/rke-prod/ghcr.io/kubewarden/policies/user-group-psp:v0.2.0"
        hostPathsPolicy:
          module: "registry01.suse:5000/rke-prod/ghcr.io/kubewarden/policies/hostpaths-psp:v0.1.5"
        capabilitiesPolicy:
          module: "registry01.suse:5000/rke-prod/ghcr.io/kubewarden/policies/capabilities-psp:v0.1.9"

```

Then check the logs.

P.S. I have also enabled authentication and authorization on the registry and configured the image pull secret.

### Environment

```markdown
- OS: SLES 15 SP4
- Architecture: x86_64
```
