### ISSUE TITLE
Extend `policies.yml` to handle context aware details

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#417]
As described inside of the [context aware RFC](https://github.com/kubewarden/rfc/blob/main/rfc/0015-context-aware-policies.md), the `policies.yml` configuration file must be updated to handle also the new `contextAwareResources` attribute that is going to be added on a per-policy basis.

This is an example of how the configuration snippet of a single policy might look like:

```yaml
namespace-validate:
  url: file:///tmp/namespace-validate-policy.wasm
  allowedToMutate: false
  contextAwareResources:
  # - apiVersion: <apiVersion>
  #   kind: <kind>
  - apiVersion: v1
    kind: Pod
  - apiVersion: apps/v1
    kind: Deployment
  - apiVersion: networking.k8s.io/v1
    Kind: Ingress
  settings:
    valid_namespace: valid
```

This information must be extracted from the configuration file and stored inside of the `Policy` object. This then needs to be fed into policy-evaluator. This information is going to be used at evaluation time to determine what kind of Kubernetes resources a Policy will be granted access to
