### ISSUE TITLE
Unable to fetch manifests from private harbor registry

### ISSUE THREAD

**Issue by jaeparker22** [kubewarden/policy-server#912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to verify the signature of a container pulled from a private harbor registry, the following error is returned by the CLI:

``` 
Error from server: error when creating "pull-harbor-success.yaml": admission webhook "clusterwide-verify-image.kubewarden.admission" denied the request: Pod verify-image-valid is not accepted: verification of image harbor.devops.<company>.com/<repo>/<project>:develop failed: Host error: Callback evaluation failure: Cannot fetch manifest of harbor.devops.<company>.com/<repo>/<project>:develop: Not authorized: url https://harbor.devops.<company>.com/v2/<repo>/<project>/manifests/develop
```
and this one by the policy-server log:
``` 
2024-03-15T15:50:38.846810Z ERROR request{method=POST uri=/validate/clusterwide-verify-image?timeout=10s version=HTTP/1.1}:validation{host="policy-server-default-647b6c8c56-lbfq7" policy_id="clusterwide-verify-image" kind="Pod" kind_group="" kind_version="v1" name="verify-image-valid" namespace="test" operation="CREATE" request_uid="d0fa899d-a975-4c47-ac27-16a7a5044c0a" resource="pods" resource_group="" resource_version="v1" subresource=""}:validate{self=PolicyEvaluator { runtime: "wapc" } settings={"modifyImagesWithDigest": Bool(true), "rule": String("PublicKey"), "signatures": Array [Object {"image": String("harbor.devops.<company>.com/<repo>/*"), "pubKeys": Array [String("-----BEGIN PUBLIC KEY-----\n<Public key data>\n-----END PUBLIC KEY-----")]}]}}: policy_evaluator::runtimes::callback: callback evaluation failed policy_id="clusterwide-verify-image" binding="kubewarden" operation="v2/verify" error="Cannot fetch manifest of harbor.devops.<company>.com/<repo>/<project>:develop: Not authorized: url https://harbor.devops.<company>.com/v2/<repo>/<project>/manifests/develop"
2024-03-15T15:50:38.856695Z  INFO request{method=POST uri=/validate/clusterwide-verify-image?timeout=10s version=HTTP/1.1}: tower_http::trace::on_response: finished processing request latency=81 ms status=200
```

### Expected Behavior

Pull the image and either accept if verified or reject if not verified.

### Steps To Reproduce

1. Generate private/public key pair with cosign
2. sign docker image
3. submit signed image to private harbor registry
4. create robot account for rancher access
6. On rancher, install kubewarden-crds and kubewarden-controller
7. create docker-registry secret in kubewarden namespace referencing robot account from step 4
8. install kubewarden-defaults, modifying helm chart to reference imagePullSecret as in this link: https://docs.kubewarden.io/operator-manual/policy-servers/private-registry
9. install verify-image-signatures policy, set it to use public key used (yaml of latest attempt at solving this on my own in Anything else)
10. Provide harbor secret to namespace you want image in
11. kubectl apply -f pull-harbor-success.yaml (contents in anything else)

### Environment

```markdown
Cosign version: 2.2.3
Harbor version: v2.10.0-6abb4eab
K8s implementation: EKS
cert-manager version: 1.14.2
Kubewarden version info:
 - kubewarden-controller: 2.0.8
 - kubewarden-crds: 1.4.5
 - kubewarden-defaults: 1.9.3
 - policy-server: 1.10.0
 - verify-image-signatures: 0.2.8
Rancher version info: 
 - Rancher: 2.8.2
 - Dashboard: 2.8.0
 - Helm: 2.16.8-rancher2
 - Machine: 0.15.0-rancher106
```

### Anything else?

Policy works when following along with this: https://www.kubewarden.io/blog/2022/05/verifying-image-signatures/
None of the default policies have had this issue.
Mutation setting seems to have no effect.
I've tried generating a robot account on harbor that has all possible permissions to no avail.

`verify-image.yaml`
includes things added by rancher. Timestamp reflects latest attempt at solving, I've been working this issue for the last month or so.
``` 
apiVersion: policies.kubewarden.io/v1
kind: ClusterAdmissionPolicy
metadata:
  annotations:
    artifacthub/pkg: verify-image-signatures/verify-image-signatures/0.2.8
  creationTimestamp: '2024-03-13T19:34:33Z'
  finalizers:
    - kubewarden
  generation: 1
  managedFields:
    - apiVersion: policies.kubewarden.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:artifacthub/pkg: {}
        f:spec:
          .: {}
          f:backgroundAudit: {}
          f:mode: {}
          f:module: {}
          f:mutating: {}
          f:namespaceSelector:
            .: {}
            f:matchExpressions: {}
          f:policyServer: {}
          f:rules: {}
          f:settings:
            .: {}
            f:modifyImagesWithDigest: {}
            f:rule: {}
            f:signatures: {}
          f:timeoutSeconds: {}
      manager: agent
      operation: Update
      time: '2024-03-13T19:34:33Z'
    - apiVersion: policies.kubewarden.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions:
            .: {}
            k:{"type":"PolicyActive"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PolicyServerConfigurationUpToDate"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PolicyUniquelyReachable"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:mode: {}
          f:policyStatus: {}
      manager: manager
      operation: Update
      subresource: status
      time: '2024-03-15T13:16:53Z'
  name: verify-image
  resourceVersion: '59372597'
  uid: 097ac356-ca34-4073-b648-6e9f49b2a030
spec:
  backgroundAudit: true
  mode: protect
  module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.2.8
  mutating: true
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
          - opa-test
  policyServer: default
  rules:
    - apiGroups:
        - ''
      apiVersions:
        - v1
      operations:
        - CREATE
        - UPDATE
      resources:
        - pods
  settings:
    modifyImagesWithDigest: true
    rule: PublicKey
    signatures:
      - image: harbor.devops.<company>.com/<repo>/*
        pubKeys:
          - |-
            -----BEGIN PUBLIC KEY-----
            <Public key data>
            -----END PUBLIC KEY-----
  timeoutSeconds: 10
status:
  conditions:
    - lastTransitionTime: '2024-03-15T13:16:53Z'
      message: The policy webhook has been created
      reason: PolicyActive
      status: 'True'
      type: PolicyActive
    - lastTransitionTime: '2024-03-13T19:35:28Z'
      message: The latest replica set is uniquely reachable
      reason: LatestReplicaSetIsUniquelyReachable
      status: 'True'
      type: PolicyUniquelyReachable
    - lastTransitionTime: '2024-03-13T19:34:33Z'
      message: Configuration for this policy is up to date
      reason: ConfigurationVersionMatch
      status: 'True'
      type: PolicyServerConfigurationUpToDate
  mode: protect
  policyStatus: active
  ```
`pull-harbor-success`
```
apiVersion: v1
kind: Pod
metadata:
  name: verify-image-valid
  namespace: test
spec:
  containers:
  - name: test-verify-image
    image: harbor.devops.<company>.com/<repo>/<project>:develop
  imagePullSecrets:
  - name: harbor-regcreds
  ```

**Comment by flavio** [comment]
I've tried to reproduce the issue, but I wasn't able. This is my testing environment, maybe this will help you understand what's wrong with your environment:

## Harbor

I'm using latest stable version: v2.11.1-6b7ecba1

I'm running it inside of a VM, using `docker compose`. I've followed the installation instructions of harbor.

I'm using self-signed certificates. I've added the CA everywhere (nodes, kubewarden's policy server CRD).

This is reachable as `harbor.local`

## Project

I've pushed `harbor.local/test/busybox:latest` as admin user. I've also signed it with a brand new cosign key I just generated.

I made the `test` project private. Only the `admin` user can pull from it.

I then created a robot account using the web UI:
- name: I gave `kubebot`, but harbor then created `robot$test+kubebot`
- expiration: never. I've picked that expiration option from the UI
- permissions: I've given only resource `repository` with `pull` and `read` permissions

The robot page:

![image](https://github.com/user-attachments/assets/fbd88f65-bec1-4ff8-904b-20cc0035c0da)

The privileges:

![image](https://github.com/user-attachments/assets/c3e0bc49-f3ad-4e18-b9ca-301b50924d89)

## Image pull secret

I've followed [these instructions](https://docs.kubewarden.io/howtos/policy-servers/private-registry#creating-the-secret) to create a secret named `secret-harbor-docker` inside of the
`default` and the `kubewarden` namespaces.

I have no problems sharing the exact commands, since this is a test environment:

```console
kubectl --namespace kubewarden create secret docker-registry secret-harbor-docker \
  --docker-username="robot\$test+kubebot" \
  --docker-password="Fw4Gr2rOokjBjm0u0f8qR68NaiaOg1zG" \
  --docker-server=harbor.local

kubectl --namespace default create secret docker-registry secret-harbor-docker \
  --docker-username="robot\$test+kubebot" \
  --docker-password="Fw4Gr2rOokjBjm0u0f8qR68NaiaOg1zG" \
  --docker-server=harbor.local
```

## Pod definition

This is the Pod I'm creating:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: signed
spec:
  containers:
    - name: busybox
      image: harbor.local/test/busybox:latest
      command: ["sleep", "3600"]
  imagePullSecrets:
    - name: secret-harbor-docker
```

Creating the pod works fine, the image is pulled from the registry.

## Kubewarden configuration

This is the configuration of the `default` Policy Server:

```yaml
apiVersion: policies.kubewarden.io/v1
kind: PolicyServer
metadata:
  name: default
spec:
  env:
    - name: KUBEWARDEN_LOG_LEVEL
      value: debug
    - name: KUBEWARDEN_DISABLE_TIMEOUT_PROTECTION
      value: "true"
  image: ghcr.io/kubewarden/policy-server:v1.16.1
  imagePullSecret: "secret-harbor-docker"
  replicas: 1
  securityContexts: {}
  serviceAccountName: policy-server
  sourceAuthorities:
    harbor.local:
      - |
        -----BEGIN CERTIFICATE-----
        MIIFuzCCA6OgAwIBAgIUClU+YvCjCNG0H50iRjil2zoP7HYwDQYJKoZIhvcNAQEN
        BQAwbTELMAkGA1UEBhMCQ04xEDAOBgNVBAgMB0JlaWppbmcxEDAOBgNVBAcMB0Jl
        aWppbmcxEDAOBgNVBAoMB2V4YW1wbGUxETAPBgNVBAsMCFBlcnNvbmFsMRUwEwYD
        VQQDDAxoYXJib3IubG9jYWwwHhcNMjQwOTIwMTUwODAyWhcNMzQwOTE4MTUwODAy
        WjBtMQswCQYDVQQGEwJDTjEQMA4GA1UECAwHQmVpamluZzEQMA4GA1UEBwwHQmVp
        amluZzEQMA4GA1UECgwHZXhhbXBsZTERMA8GA1UECwwIUGVyc29uYWwxFTATBgNV
        BAMMDGhhcmJvci5sb2NhbDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
        ALq4Po9ItDF4xI/Ides4zWs6VHDPatQ1i7N1nWLQIWgqgmKQdDuszyeApwUJiIjH
        f2DAHToTFtFnTgbcpW0KL9JHP/Q1FtIXIUMSo6xYJLCoc++5vth6lWEeZdTkBHQW
        Gkv52VSa7BYaV84rZD/THgKxbMJ+IG3yxWXE5eQh6a3MA/PXdmNbeyxoXvmAzUEM
        tI6NoK2SG96MzDjqVVrx0muHrLOW/3bBWoA6DoWJcluBzRSwuY69iY6y/987SECm
        N7FX5w5sb6Zvrkij+OlELQG2GurZ+qWH3GvUGsEUkxUavnFsu1qifuopUz+aNn7y
        j2yAb3Xr/3FoAet88YgOeJB35DhtamdjsDDXqhk3RindduYe/YhD3p7oyrv4f8U+
        kDMUHfCzsE0fScXKdkDIS6mROXfSmMuZzmUkENrKHQhd8Dqvw5lekW8I0yW+9rIg
        QZEektGRJzycazg8kai2coeWJ1HKHcOamq0eNoxx3OdFVfwxuE0d0fHYKLVN2A5r
        oEoI4loGcwgFAevoMltmwc0pKlfpPBDoKiY3agYWO0OOBV8yxXzcq2jbsl6MAX+F
        V5epSlPKQkocgRJPQ7a3L6otNVr5NWGEcp6RLtuDahHGTysO/iJUXCGzEXX0qi6E
        bLZB46xM5xIIZj3/oLgKcA/yZpeYmE5Jt2/AtJ+im1I3AgMBAAGjUzBRMB0GA1Ud
        DgQWBBSIM5+1esV2zuUK+AVIfNl7vX5WRDAfBgNVHSMEGDAWgBSIM5+1esV2zuUK
        +AVIfNl7vX5WRDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBDQUAA4ICAQBc
        w5bbg4JUn3tNKGtFn2YHXOIfOOOd7PMYYgM4X9miTNq6+XQjQsZxojoSab6BupVS
        m5dQshXbLjXjgY4Lvc9gBhoSmn/L5eaV/17p80v27tU1UjmczGIkIox1xlXQB3rO
        GglaJEf4cfVfj16THNSQpXQqmMiCTnJxvTp0QqBnxNstBJLszfb0Zr8SR+cfCiXV
        GztGnerCIqyvEJKjmK+tqijoxqpYbHBFpN8bwiCL9O+h/aFV0LvgIZxTwgMDoocn
        i26XTbtECAbz+Az4UUPO4NCfN8zdStRPBjRshQHonT1MgtaUqi5uhX6In23O9rhT
        OI5OA47DUjAoA/ctkH87hvpuJ/qKGDrrk7IWRzL2BO0LxPhDQxCKyvypP6quqUAr
        qciv4waTX01n06eKCCl6+U7bwCyjIgsmmJJjD6slvfhCsqr+1eHHsHat4J5HjXAT
        MwSMwJeJwXMAJPZo/l5jvYMa8JCXSqGm6qIkSTbvy0uGIv7m43i1yeDnw6ohQc2q
        lknGeXD5k2abdEVisvb14rpp3HvGfkZ1q5RMLwHGUNlRT/N28fp2ohpN6z5/wrlL
        +vv/ZNXA3jjm+9xDxCUGZ1cTdBNQipsdnLp86MUO7kOQeLQgn43pi8662JYhnCPq
        gsDmRZ6kaPg4xIO7uSb/Bl+/fe2Ok7zPElolpLCoaw==
        -----END CERTIFICATE-----
```

## Rejecting the pod creation

First of all, I made sure the Pod `signed` (the one shown abobe) was not running inside of the `default` namespace.

Then I deployed the following `AdmissionPolicy`:

```yaml
apiVersion: policies.kubewarden.io/v1
kind: AdmissionPolicy
metadata:
  name: demo
  namespace: default
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
  settings:
    modifyImagesWithDigest: false
    signatures:
      - image: "*"
        pubKeys: # a key that didn't sign the image
          - |
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyg65hiNHt8FXTamzCn34IE3qMGcV
            yQz3gPlhoKq3yqa1GIofcgLjUZtcKlUSVAU2/S5gXqyDnsW6466Jx/ZVlg==
            -----END PUBLIC KEY-----
```

I waited for the policy to be active, then I created the Pod:

```console
kubectl apply -f signed-pod.yml
Error from server: error when creating "signed-pod.yml": admission webhook "namespaced-default-demo.kubewarden.admission" denied the request: Resource signed is not accepted: verification of image harbor.local/test/busybox:latest failed: Host error: Callback evaluation failure: Image verification failed: missing signatures
The following constraints were not satisfied:
kind: pubKey
owner: null
key: |
  -----BEGIN PUBLIC KEY-----
  MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEyg65hiNHt8FXTamzCn34IE3qMGcV
  yQz3gPlhoKq3yqa1GIofcgLjUZtcKlUSVAU2/S5gXqyDnsW6466Jx/ZVlg==
  -----END PUBLIC KEY-----
annotations: null
```

Just to be sure, I deleted the policy I defined above and I created another one:

```yaml
apiVersion: policies.kubewarden.io/v1
kind: AdmissionPolicy
metadata:
  name: demo
  namespace: default
spec:
  rules:
    - apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["pods"]
      operations:
        - CREATE
        - UPDATE
  module: ghcr.io/kubewarden/policies/verify-image-signatures:v0.3.0
  settings:
    modifyImagesWithDigest: false
    signatures:
      - image: "*"
        pubKeys: # the key that signed the image
          - |
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE0FH4J+y4trDIls6XfgtJvjW2FYBA
            0WK2JKWEORpc7pihx82uWdNftOg9qL+8o9UV4V9FODLQNfd/weLgPBdRYg==
            -----END PUBLIC KEY-----
```

I waited for the policy to be enforced, then I tried to create the Pod again:

```console
kubectl apply -f signed-pod.yml
pod/signed created
```

The Pod was created and was running fine:

```console
kubectl get pods
NAME     READY   STATUS    RESTARTS   AGE
signed   1/1     Running   0          22s
```

## Recap

I think there's something wrong with your setup. I hope the detailed explanation from above will help you finding what has been misconfigured.
