### ISSUE TITLE
Allow verification of policies using sigstore

### ISSUE THREAD

**Issue by flavio** [kubewarden/policy-server#98]
Kubewarden policies are WebAssembly modules stored inside of OCI registries. Users can reference them by shasum if wanted, but it would way better to provide a stronger way to verify the policies before using them.

[sigstore](https://sigstore.dev) is a new standard that allows the signature and verification of container images and OCI artifacts.

We should leverage sigstore to provide a way to verify policies before their execution.

## Use case

> As an administrator,
> I want all the Kubewarden policies loaded in production to be signed with a certain key,
> so that unverified policies are not loaded.

## How that should work

* Policies are signed using `cosign` or some equivalent tool. 
* Policy Server has a configuration flag that enforces all the policies mentioned inside of its configuration file to be signed
* PolicyServer reads a list of keys and annotations from a verification.yaml file. This file will be mounted as a Secret for PolicyServer to use it. Example:
```yaml
verification-keys:
  key-name-irrelevant: |
        -----BEGIN PUBLIC KEY-----
        MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEX0HFTtCfTtPmkx5p1RbtwDE1EVzu
        wjQs1cCRKb5Pz/yUspkQsN3FO4iyWodCy5j3o0CdIJD/1gvq98pf4IG9tA==
        -----END PUBLIC KEY-----
verification-annotations: # optional
  env: prod
```
* Policy Server exits with an error if one or more policies fail the verification

Note well: this is a rough idea about how this feature should work. We definitely need to spend more time discussing how that should work. Feedback is welcome!

**Comment by viccuad** [comment]
Given that each policy can be signed with a different key and a list of annotations, I will go with the approach of adding those fields as optional to policy-server's policies.yaml:
```yaml
psp-apparmor:
  url: registry://ghcr.io/kubewarden/policies/psp-apparmor:v0.1.3
psp-capabilities:
  url: registry://ghcr.io/kubewarden/policies/psp-capabilities:v0.1.2
  verification-keys:
    - key: |
         pub key
  verification-annotations:
      - env: prod
  settings:
    allowed_capabilities: ["*"]
    required_drop_capabilities: ["KILL"]
```
I expect these fields to be present in the ClusterAdmissionPolicy CRD in the future.

I think it would be useful to pass policy-server a list of tuples of (key, URI, annotations) to verify policies with. That way, no need to state each policy verification information, and URIs can be configured by default so they are verified (e.g: all policies under hub.kubewarden.io, or other domain). Yet I will not add this to the PR for this card.
